---
# - name: Stop nginx before obtaining cert
#   service:
#     name: nginx
#     state: stopped
#   ignore_errors: yes
#   become: yes

# - name: Run certbot to get cert
#   command: > 
#     certbot 
#     certonly 
#     -d {{ domain }} 
#     --agree-tos 
#     -m {{ email }} 
#     --standalone
#     -n
#   when: lets_encrypt
#   become: yes

- name: Install nginx
  package:
    name: nginx
    state: present
  become: yes

- name: Write site configuration file templates
  template:
    src: "{{ site_conf_file }}.j2"
    dest: "/etc/nginx/conf.d/{{ site_conf_file }}"
  loop:
    - www.mickjohn.com.conf
    - games.mickjohn.com.conf
  loop_control:
    loop_var: site_conf_file
  become: yes

- name: Write config template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: yes

- name: Upload files
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: "{{ item.value.mode | default(omit) }}"
  with_dict: "{{ files }}"
  become: yes

- name: Restart and enable nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
  become: yes
