---
- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install pip & docker requirements
  apt:
    name: 
      - python-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: yes

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  become: yes

- name: Install docker
  apt:
    name: docker-ce
    state: installed
    update_cache: yes
  become: yes

- name: Install python libraries
  pip:
    name:
      - docker
      - requests
      - docker-compose
  become: yes
      
