---
- set_fact:
    package_name_and_version: "{{ package_name }}_{{ version }}.deb"

- name: Check that service is registered
  shell: ls /lib/systemd/system/{{ service_name }}.service
  register: service_exists_result
  ignore_errors: yes

- name: stop webserver
  service:
    name: motorsport_calendar_webserverd
    state: stopped
  become: true
  when: service_exists_result.rc == 0

- name: Copy deb package
  copy:
    src: "{{local_dev_dir}}/{{ package_name_and_version }}"
    dest: "/tmp"

- name: Install a .deb package
  apt:
    deb: "/tmp/{{ package_name_and_version }}"
  become: yes

- name: Render api config template
  template:
    src: webserver_config.j2
    dest: "/etc/motorsport_calendar_webserver/config.yml"

- name: Render service config template
  template:
    src: service.j2
    dest: /lib/systemd/system/{{ service_name }}.service
  become: yes

- name: reload systemd config
  shell: systemctl daemon-reload
  become: true

- name: start and enable webserver
  service:
    name: "{{ service_name }}"
    enabled: yes
    state: started
  become: true

