---
- name: Install 'software-properties-common'
  package:
    update_cache: yes
    name: software-properties-common
    state: latest
  become: yes

- name: Add 'Lets Encrypt' PPA repository
  apt_repository:
    repo: ppa:certbot/certbot
  become: yes

- name: Install 'python-certbot-nginx'
  package:
    update_cache: yes
    name: python-certbot-nginx
    state: latest
  become: yes
