---
# enable_ssl: yes
# lets_encrypt: yes
files:
  ssl_key:
    src: key.pem
    dest: /etc/ssl/private/key.pem
    owner: root
    group: root
    mode: 0644

  ssl_cert:
    src: cert.pem
    dest: /etc/ssl/certs/cert.pem
    owner: root
    group: root
    mode: 0640
